### ISSUE TITLE
A parameter cannot be found that matches parameter name 'Encoding'

### ISSUE THREAD

**Issue by Bifidus-Activus** [code-pm/CrouchingRancor.ModExtractor#2]
I just modified code to run on my Computer:

Original line 120:
**$mods | ConvertTo-Json | Set-Content  -Encoding UTF8 -Path "$($PSScriptRoot)\mods.json"**
return error about -Encoding (A parameter cannot be found that matches parameter name 'Encoding')

Modified line 120:
**$mods | ConvertTo-Json | Set-Content -LiteralPath "$($PSScriptRoot)\mods.json" -Encoding UTF8**
work like a charm!

Spend 4 hours to find it (doesn't know powershell before).

Good luck ;)

**Comment by codepm** [comment]
Excellent! Thanks for sharing!
